/* 
* To change this template, choose Tools | Templates 
* and open the template in the editor. 
*/ 

/* 
* Calculator.java 
* 
* Created on Apr 29, 2010, 6:15:35 PM 
*/ 

/** 
* 
* @author Shubham
*/ 
public class Calculator extends javax.swing.JFrame { 
int r1; 
int r2; 
String option; 
int result; 
/** Creates new form Calculator */ 
public Calculator() { 
initComponents(); 
} 

/** This method is called from within the constructor to 
* initialize the form. 
* WARNING: Do NOT modify this code. The content of this method is 
* always regenerated by the Form Editor. 
*/ 
@SuppressWarnings("unchecked") 
// <editor-fold defaultstate="collapsed" desc="Generated Code"> 
private void initComponents() { 

jButton1 = new javax.swing.JButton(); 
jButton2 = new javax.swing.JButton(); 
jButton3 = new javax.swing.JButton(); 
jButton4 = new javax.swing.JButton(); 
jButton5 = new javax.swing.JButton(); 
jButton6 = new javax.swing.JButton(); 
jButton7 = new javax.swing.JButton(); 
jButton8 = new javax.swing.JButton(); 
jButton9 = new javax.swing.JButton(); 
jButton10 = new javax.swing.JButton(); 
jButton11 = new javax.swing.JButton(); 
jButton12 = new javax.swing.JButton(); 
jButton13 = new javax.swing.JButton(); 
jButton14 = new javax.swing.JButton(); 
jButton15 = new javax.swing.JButton(); 
CalcTF = new javax.swing.JTextField(); 

setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE); 

jButton1.setText("1"); 
jButton1.addActionListener(new java.awt.event.ActionListener() { 
public void actionPerformed(java.awt.event.ActionEvent evt) { 
DigitPressed(evt); 
} 
}); 

jButton2.setText("2"); 
jButton2.addActionListener(new java.awt.event.ActionListener() { 
public void actionPerformed(java.awt.event.ActionEvent evt) { 
DigitPressed(evt); 
} 
}); 

jButton3.setText("3"); 
jButton3.addActionListener(new java.awt.event.ActionListener() { 
public void actionPerformed(java.awt.event.ActionEvent evt) { 
DigitPressed(evt); 
} 
}); 

jButton4.setText("4"); 
jButton4.addActionListener(new java.awt.event.ActionListener() { 
public void actionPerformed(java.awt.event.ActionEvent evt) { 
DigitPressed(evt); 
} 
}); 

jButton5.setText("5"); 
jButton5.addActionListener(new java.awt.event.ActionListener() { 
public void actionPerformed(java.awt.event.ActionEvent evt) { 
DigitPressed(evt); 
} 
}); 

jButton6.setText("6"); 
jButton6.addActionListener(new java.awt.event.ActionListener() { 
public void actionPerformed(java.awt.event.ActionEvent evt) { 
DigitPressed(evt); 
} 
}); 

jButton7.setText("7"); 
jButton7.addActionListener(new java.awt.event.ActionListener() { 
public void actionPerformed(java.awt.event.ActionEvent evt) { 
DigitPressed(evt); 
} 
}); 

jButton8.setText("8"); 
jButton8.addActionListener(new java.awt.event.ActionListener() { 
public void actionPerformed(java.awt.event.ActionEvent evt) { 
DigitPressed(evt); 
} 
}); 

jButton9.setText("9"); 
jButton9.addActionListener(new java.awt.event.ActionListener() { 
public void actionPerformed(java.awt.event.ActionEvent evt) { 
DigitPressed(evt); 
} 
}); 

jButton10.setText("0"); 
jButton10.addActionListener(new java.awt.event.ActionListener() { 
public void actionPerformed(java.awt.event.ActionEvent evt) { 
DigitPressed(evt); 
} 
}); 

jButton11.setText("="); 
jButton11.addActionListener(new java.awt.event.ActionListener() { 
public void actionPerformed(java.awt.event.ActionEvent evt) { 
jButton11ActionPerformed(evt); 
} 
}); 

jButton12.setText("+"); 
jButton12.addActionListener(new java.awt.event.ActionListener() { 
public void actionPerformed(java.awt.event.ActionEvent evt) { 
jButton12ActionPerformed(evt); 
} 
}); 

jButton13.setText("-"); 
jButton13.addActionListener(new java.awt.event.ActionListener() { 
public void actionPerformed(java.awt.event.ActionEvent evt) { 
jButton13ActionPerformed(evt); 
} 
}); 

jButton14.setText("/"); 
jButton14.addActionListener(new java.awt.event.ActionListener() { 
public void actionPerformed(java.awt.event.ActionEvent evt) { 
jButton14ActionPerformed(evt); 
} 
}); 

jButton15.setText("*"); 
jButton15.addActionListener(new java.awt.event.ActionListener() { 
public void actionPerformed(java.awt.event.ActionEvent evt) { 
jButton15ActionPerformed(evt); 
} 
}); 

javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane()); 
getContentPane().setLayout(layout); 
layout.setHorizontalGroup( 
layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING) 
.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup() 
.addGap(97, 97, 97) 
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING) 
.addComponent(CalcTF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE) 
.addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup() 
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING) 
.addGroup(layout.createSequentialGroup() 
.addComponent(jButton4) 
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED) 
.addComponent(jButton5)) 
.addGroup(layout.createSequentialGroup() 
.addComponent(jButton9) 
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED) 
.addComponent(jButton8))) 
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED) 
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false) 
.addGroup(layout.createSequentialGroup() 
.addComponent(jButton7) 
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED) 
.addComponent(jButton12)) 
.addGroup(layout.createSequentialGroup() 
.addComponent(jButton6) 
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED) 
.addComponent(jButton13, 0, 0, Short.MAX_VALUE)))) 
.addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup() 
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false) 
.addComponent(jButton10, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE) 
.addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING)) 
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED) 
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING) 
.addGroup(layout.createSequentialGroup() 
.addComponent(jButton2) 
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED) 
.addComponent(jButton3)) 
.addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)) 
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED) 
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING) 
.addComponent(jButton14, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE) 
.addComponent(jButton15, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)))) 
.addGap(126, 126, 126)) 
); 
layout.setVerticalGroup( 
layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING) 
.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup() 
.addContainerGap(69, Short.MAX_VALUE) 
.addComponent(CalcTF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE) 
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED) 
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE) 
.addComponent(jButton7) 
.addComponent(jButton8) 
.addComponent(jButton9) 
.addComponent(jButton12)) 
.addGap(6, 6, 6) 
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE) 
.addComponent(jButton4) 
.addComponent(jButton5) 
.addComponent(jButton6) 
.addComponent(jButton13)) 
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED) 
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE) 
.addComponent(jButton1) 
.addComponent(jButton2) 
.addComponent(jButton3) 
.addComponent(jButton15)) 
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED) 
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE) 
.addComponent(jButton10) 
.addComponent(jButton11) 
.addComponent(jButton14)) 
.addGap(78, 78, 7) )
); 

pack(); 
}// </editor-fold> 

private void DigitPressed(java.awt.event.ActionEvent evt) { 
String txt =evt.getActionCommand(); 
String calcval =CalcTF.getText(); 
if (txt.equals("0")) 
CalcTF.setText(calcval +"0"); 
if (txt.equals("1")) 
CalcTF.setText(calcval +"1"); 
if (txt.equals("2")) 
CalcTF.setText(calcval +"2"); 
if (txt.equals("3")) 
CalcTF.setText(calcval +"3"); 
if (txt.equals("4")) 
CalcTF.setText(calcval +"4"); 
if (txt.equals("5")) 
CalcTF.setText(calcval +"5"); 
if (txt.equals("6")) 
CalcTF.setText(calcval +"6"); 
if (txt.equals("7")) 
CalcTF.setText(calcval +"7"); 
if (txt.equals("8")) 
CalcTF.setText(calcval +"8"); 
if (txt.equals("9")) 
CalcTF.setText(calcval +"9"); 

} 

private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) { 
r1=Integer.parseInt(CalcTF.getText()); 
option = jButton12.getText(); 
CalcTF.setText(""); 
} 
private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) { 
r1=Integer.parseInt(CalcTF.getText()); 
option = jButton13.getText(); 
CalcTF.setText(""); 
} 

private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) { 
r1=Integer.parseInt(CalcTF.getText()); 
option = jButton15.getText(); 
CalcTF.setText(""); 
} 

private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) { 
r1=Integer.parseInt(CalcTF.getText()); 
option = jButton14.getText(); 
CalcTF.setText(""); 
} 

private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) { 
r2=Integer.parseInt(CalcTF.getText()); 
if (option.equals("+")) 
result=r1+r2; 
if (option.equals("-")) 
result=r1-r2; 
if (option.equals("*")) 
result=r1*r2; 
if (option.equals("/")) 
result=r1/r2; 
CalcTF.setText(result+" "); 
} 



/** 
* @param args the command line arguments 
*/ 
public static void main(String args[]) { 
java.awt.EventQueue.invokeLater(new Runnable() { 
public void run() { 
new Calculator().setVisible(true); 
} 
}); 
} 

// Variables declaration - do not modify 
private javax.swing.JTextField CalcTF; 
private javax.swing.JButton jButton1; 
private javax.swing.JButton jButton10; 
private javax.swing.JButton jButton11; 
private javax.swing.JButton jButton12; 
private javax.swing.JButton jButton13; 
private javax.swing.JButton jButton14; 
private javax.swing.JButton jButton15; 
private javax.swing.JButton jButton2; 
private javax.swing.JButton jButton3; 
private javax.swing.JButton jButton4; 
private javax.swing.JButton jButton5; 
private javax.swing.JButton jButton6; 
private javax.swing.JButton jButton7; 
private javax.swing.JButton jButton8; 
private javax.swing.JButton jButton9; 
// End of variables declaration 

} 